### ISSUE TITLE
follow-up

### ISSUE THREAD

**Issue by 34fathombelow** [chengkuangan/etcdbk#2]
@34fathombelow 

thank you for your suggestion, it reduce the size from 970MB to 549MB !

These are changes what I would suggest on top of yours
```
...
RUN apk add --no-cache --virtual .build-deps git go
RUN apk add --no-cache jq tzdata bash \
...
```
We need the `tzdata` for timezone to work. 

I am not sure why I encountered this error if I remove `bash`, also updated `run_backup.sh` to use `sh` by doing so. The following is the error I encountered without using `bash`. Do you have similar issue? (doing local test on macos)

```
echo "$(<${KUBE_PATH}/kubectl.sha256)  ${KUBE_PATH}/kubectl" | sha256sum -c
/data/bin/kubectl: FAILED
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
```
Anyway, if we keep `bash`, it does not create any impact on container image size. Should we just keep it?

_Originally posted by @chengkuangan in https://github.com/chengkuangan/etcdbk/pull/1#pullrequestreview-885387664_

**Comment by 34fathombelow** [comment]
@chengkuangan 

After running further test and checking into the error you reported.  I was not getting this error on my local cluster at home.  Running it on a local instance such as Kind I did get the same error.  After digging around I discovered it to be a DNS problem.  It is a common issue with Alpine based images on Kubernetes. Due to it using the musl library, it stops searching possible domains specified in the search directive of `/etc/resolve.conf`  
 
You can run a container on your local macos cluster to test:
kubectl run -it --tty --rm debug --image=alpine --restart=Never -- wget https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl
```
wget: bad address 'dl.k8s.io
```

Run the same command with Busybox image:
kubectl run -it --tty --rm debug --image=busybox --restart=Never -- wget https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl
```
kubectl     100% |************************************************************************| 44.7M  0:00:00 ETA
'kubectl' saved
```
There are a few work arounds to fix this
1. We can use a dnsPolicy in the podSpec of the manifest (etcdbk.yaml) :
```yml
dnsConfig:
  options:
    - name: ndots
      value: '1'
```
2. Add to the Script and modify `/etc/resolve.conf` to make the ndots parameter to contain the value of '1'
3. Add to the `/etc/hosts` file a IP Address hard coded for `dl.k8s.io`.  ( Which I do not recommend )
4. Rebase the container Image off something other than Alpine.

Let me know what you think.  Maybe use option 1 as a temporary remediation.

**Comment by chengkuangan** [comment]
@34fathombelow 

I think is it not the issue with DNS. It works fine for me. The problem only happens with comparing the `sha` signature at this line. Somehow the `$?` is equal to `1`. This is only happening when using `sh` but not `bash`

```
echo "$(<${KUBE_PATH}/kubectl.sha256)  ${KUBE_PATH}/kubectl" | sha256sum -cs
``` 
The following shows DNS works fine for me in `kubernetes`.
```
kubectl run -it --tty --rm debug --image=alpine --restart=Never -- wget https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl
If you don't see a command prompt, try pressing enter.
kubectl              100% |*************************************************************************************************************************************************************************************************************| 44.7M  0:00:00 ETA
'kubectl' saved
pod "debug" deleted
```

Anyway, we already using `bash` and works fine. So we just go with `bash`.

For your case, probably is your DNS settings is not properly configured. Maybe you can want to compare your steps with my steps [here](https://braindose.blog/2021/12/31/install-kubernetes-raspberry-pi/#preparing-ubuntu-os-for-kubernetes). Note that I am using Ubuntu and may not 100% applicable but should give you a hint or so.

**Comment by chengkuangan** [comment]
closing as no changes is required

**Comment by 34fathombelow** [comment]
@chengkuangan 

Sorry for the late response.  I misunderstood the error you were having.   I was only having this issue with Kind in testing. Pretty silly how it was the same message but a different issue.  Things are working great on my cluster at home.  Thanks again for your prompt response and all your awesome work. 

I have been playing around with with a multi-stage build of the Dockerfile.  Feel free to check it out on my fork in the multistage-build branch.  The image is down to 143MB uncompressed.  We also have the option to add the kubectl binary to the build to support arm64/amd64 which would only add an additional 50MB +/- a few.  I would rather not add this, giving the user a choice to use a different version of kubectl without a rebuild of the image.

Let me know what you think if you have time, all is appreciated

**Comment by chengkuangan** [comment]
@34fathombelow 

Interesting! Will take a look at that sometime over the weekend ... 

btw, curious what are you using your k8s on RPI for?

**Comment by 34fathombelow** [comment]
@chengkuangan 

Right now just running a few applications on it.  It consists of 4 RPI's, 1 control-plane, 3 worker nodes, and a AMD64 worker node.  I'm in the process of migrating all my home services hosted on a few VMs into the Cluster.  Planning to add an additional AMD64 or two nodes, then converting two of the Pi's into control-planes.  It is mainly just a hobby project of mine.

**Comment by chengkuangan** [comment]
@34fathombelow 

Great move! 

I got Nextcloud and Wordpress so far. plus things like NFS storage, prom, Grafana... 

3 CP, 2 workers, plan to add on more when RPI4 stock available with calm price. I crashed them when I tried to run my demo on Kafka, quarkus, etc ... too heavy ... but I think RPI4 with k8s can really fly

**Comment by 34fathombelow** [comment]
@chengkuangan 

Sounds awesome!! I agree the RPI4 are a good bang for the buck, but very limited to heavier workloads.  The price and availability of them is a bit insane right now. 

Quick question, have you had a issue with etcdbk not being scheduled on a control-plain?  I had to add a nodeAffinity and toleration to my manifest.  If it was assigned to a worker node it would not be able to mount `/etc/kubernetes/pki/etcd`.
This is what I used:
```yaml
spec:
  template:
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists

      containers:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
```

**Comment by chengkuangan** [comment]
@34fathombelow 

oh dear, sorry, this is a huge mistake that I have done. It's working on my cluster is because I have configured my control plane to be schedulable. I just checked it so happens every time I deployed, it scheduled at the control plane.

This is a huge architectural mistake. It should have been deployed as [DemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/). But we need to test it out while at the same time deployed to control plane we need to make sure it is only scheduled to control plane only and always 1 POD at a time.

**Comment by 34fathombelow** [comment]
You can not have a Cronjob set as a Demonset, as they are different types of Kinds.
Maybe this is a better approach:
```yaml
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: component
            operator: In
            values:
            - etcd

containers:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
```
This would ensure that the pod must get deployed only on a node that has etcd on it.  We must add the tolerations to make sure they are schedulable on the control-planes.
